/*
Copyright 2020 The Knative Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
	v1alpha1 "knative.dev/eventing-contrib/rocketmq/pkg/apis/messaging/v1alpha1"
)

// FakeRocketmqChannels implements RocketmqChannelInterface
type FakeRocketmqChannels struct {
	Fake *FakeMessagingV1alpha1
	ns   string
}

var rocketmqchannelsResource = schema.GroupVersionResource{Group: "messaging.knative.dev", Version: "v1alpha1", Resource: "rocketmqchannels"}

var rocketmqchannelsKind = schema.GroupVersionKind{Group: "messaging.knative.dev", Version: "v1alpha1", Kind: "RocketmqChannel"}

// Get takes name of the rocketmqChannel, and returns the corresponding rocketmqChannel object, and an error if there is any.
func (c *FakeRocketmqChannels) Get(name string, options v1.GetOptions) (result *v1alpha1.RocketmqChannel, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(rocketmqchannelsResource, c.ns, name), &v1alpha1.RocketmqChannel{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.RocketmqChannel), err
}

// List takes label and field selectors, and returns the list of RocketmqChannels that match those selectors.
func (c *FakeRocketmqChannels) List(opts v1.ListOptions) (result *v1alpha1.RocketmqChannelList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(rocketmqchannelsResource, rocketmqchannelsKind, c.ns, opts), &v1alpha1.RocketmqChannelList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.RocketmqChannelList{ListMeta: obj.(*v1alpha1.RocketmqChannelList).ListMeta}
	for _, item := range obj.(*v1alpha1.RocketmqChannelList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested rocketmqChannels.
func (c *FakeRocketmqChannels) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(rocketmqchannelsResource, c.ns, opts))

}

// Create takes the representation of a rocketmqChannel and creates it.  Returns the server's representation of the rocketmqChannel, and an error, if there is any.
func (c *FakeRocketmqChannels) Create(rocketmqChannel *v1alpha1.RocketmqChannel) (result *v1alpha1.RocketmqChannel, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(rocketmqchannelsResource, c.ns, rocketmqChannel), &v1alpha1.RocketmqChannel{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.RocketmqChannel), err
}

// Update takes the representation of a rocketmqChannel and updates it. Returns the server's representation of the rocketmqChannel, and an error, if there is any.
func (c *FakeRocketmqChannels) Update(rocketmqChannel *v1alpha1.RocketmqChannel) (result *v1alpha1.RocketmqChannel, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(rocketmqchannelsResource, c.ns, rocketmqChannel), &v1alpha1.RocketmqChannel{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.RocketmqChannel), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeRocketmqChannels) UpdateStatus(rocketmqChannel *v1alpha1.RocketmqChannel) (*v1alpha1.RocketmqChannel, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(rocketmqchannelsResource, "status", c.ns, rocketmqChannel), &v1alpha1.RocketmqChannel{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.RocketmqChannel), err
}

// Delete takes name of the rocketmqChannel and deletes it. Returns an error if one occurs.
func (c *FakeRocketmqChannels) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(rocketmqchannelsResource, c.ns, name), &v1alpha1.RocketmqChannel{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeRocketmqChannels) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(rocketmqchannelsResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1alpha1.RocketmqChannelList{})
	return err
}

// Patch applies the patch and returns the patched rocketmqChannel.
func (c *FakeRocketmqChannels) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.RocketmqChannel, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(rocketmqchannelsResource, c.ns, name, pt, data, subresources...), &v1alpha1.RocketmqChannel{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.RocketmqChannel), err
}
